default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: messaging_service_development

test:
  <<: *default
  database: messaging_service_test

production:
  <<: *default
  database: messaging_service_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
